<script lang="ts">
  import Popup from "$lib/components/popups/Popup.svelte";

  type Props = {
    open: boolean;
    onClose: () => void;
  };

  let { open, onClose }: Props = $props();
</script>

<Popup
  {open}
  title="Welcome to Deployable Knowledge"
  id="welcome-popup"
  contentLabel="Welcome and setup guide"
  width="640px"
  {onClose}
>
  <div class="welcome">
    <p class="intro">
      This app runs entirely on your machine - documents, embeddings, and chat all stay
      local. A couple of things need to be set up first.
    </p>

    <section>
      <h3>1. Install Ollama (required)</h3>
      <p>
        Chat responses are generated by a local model served through
        <a href="https://ollama.com" target="_blank" rel="noreferrer">Ollama</a>. Without it
        running, the assistant can't respond.
      </p>
      <ol>
        <li>Download and install Ollama from <a href="https://ollama.com" target="_blank" rel="noreferrer">ollama.com</a>.</li>
        <li>
          Pull the default model:
          <code>ollama pull granite4:350m</code>
        </li>
        <li>Leave Ollama running in the background (it listens on <code>localhost:11434</code>).</li>
      </ol>
      <p class="note">
        You can swap in a different model or provider later from Settings - this is just
        the one the app is configured to use out of the box.
      </p>
    </section>

    <section>
      <h3>2. First-time project setup</h3>
      <ol>
        <li><code>npm install</code></li>
        <li>
          <code>npm run dev</code> - this also pushes the database schema automatically the
          first time it runs.
        </li>
      </ol>
    </section>

    <section>
      <h3>3. Upload documents</h3>
      <p>
        Open the Document Library window to browse for a file, or copy a file on your
        computer and paste it directly into the window.
      </p>
    </section>

    <div class="actions">
      <button type="button" onclick={onClose}>Get Started</button>
    </div>
  </div>
</Popup>

<style>
  .welcome {
    display: grid;
    max-height: min(720px, calc(100vh - 80px));
    overflow: auto;
    color: var(--text);
    gap: 16px;
  }

  .intro {
    margin: 0;
    color: var(--muted);
    font-size: 13px;
  }

  section {
    display: grid;
    gap: 8px;
  }

  h3 {
    margin: 0;
    font-size: 13px;
  }

  p {
    margin: 0;
    color: var(--muted);
    font-size: 12px;
    line-height: 1.5;
  }

  .note {
    font-style: italic;
  }

  ol {
    display: grid;
    margin: 0;
    padding-left: 20px;
    gap: 6px;
    color: var(--text);
    font-size: 12px;
    line-height: 1.5;
  }

  a {
    color: var(--accent);
  }

  code {
    border: 1px solid var(--border);
    border-radius: 6px;
    background: hsl(var(--h) var(--sat) var(--l-panel));
    padding: 1px 6px;
    font-size: 11px;
  }

  .actions {
    display: flex;
    justify-content: flex-end;
  }

  .actions button {
    border: 1px solid var(--border);
    border-radius: 10px;
    background: hsl(var(--h) var(--sat) var(--l-panel));
    color: var(--text);
    cursor: pointer;
    padding: 6px 14px;
  }

  .actions button:hover {
    border-color: hsl(var(--h) var(--sat) calc(var(--l-border) + 8%));
  }
</style>
